# Portail Serveur de r√©pertoires
http:
  routers:
    nginx:
      entryPoints: 
      - websecure
      # tous les flux vont sur nginx
      # rule: "Host(`pbillerot.freeboxos.fr`) || Host(`pbillerot.freeboxos.fr`) && PathPrefix(`/`)"
      rule: "Host(`pbillerot.freeboxos.fr`) && PathPrefix(`/`)"
      service: nginx

  services:
    nginx:
      loadBalancer:
        servers:
        - url: "http://172.17.0.1:7603/"
